version: '3.9'

services:
  api:
    build:
      context: ./scribble.API
    container_name: scribble-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  client:
    build:
      context: ./scribble-client
    container_name: scribble-client
    ports:
      - "80:80"
    depends_on:
      - api
